# overrides of built-in oh-my-zsh / git plugin aliases
alias gb="git --no-pager branch"
alias lsa="ls -a"

# other aliases
alias aliasv="ccat $ZSH_CUSTOM/aliases.zsh"
alias aliase="code $ZSH_CUSTOM/aliases.zsh"
alias aliasg="alias | grep -i"
alias reload="exec zsh && clear"
alias latest="git -C $ZSH pull && reload"
alias repos="cd ~/repos"
alias gs="git status"
alias lsg="ls | grep"
alias cdu="cd ../"
alias cat="ccat --bg=dark"
alias catg="cat | grep"
alias kubetcl="minikube kubectl --"
alias cb="cargo build"
alias ct="cargo test"
alias cr="cargo run"